### ISSUE TITLE
Enabled caching in ExtMgr. also caches Formlabel

### ISSUE THREAD

**Issue by ZYZ64738** [pascal20997/pr_googlecse#1]
If caching is enabled  in ExtMgr. the complete form is cached.
In a multilingual Typo3-setting the formlabel never changes because the whole content is cached instead the searchresult-list only.

**Comment by pascal20997** [comment]
Hey @ZYZ64738 thanks for your input. You're right this shouldn't happen but it's like you described. I'm thinking about either extending the cache identifier and add the language code into it - so that there is one cache entry for each language - or caching the result from the API only. The benefit of caching the rendered template is performance
